### ISSUE TITLE
Readthedocs is unhappy with the extension

### ISSUE THREAD

**Issue by astronomyk** [jpsenior/sphinx-execute-code#4]
Hi,

Thanks for writing the package!

Just an FYI. When running on the read-the-docs system and on my own system (py3.6 / sphinx 1.6.7) I get the following error:

```
"/home/docs/checkouts/readthedocs.org/user_builds/anisocado/envs/latest/lib/python3.7/site-packages/sphinx_execute_code/__init__.py", line 81

   exec code
            ^
SyntaxError: Missing parentheses in call to 'exec'
```

I guess this was missed during the upgrade to py3.

Cheers,
K

Full traceback from readthedocs:

```
Running Sphinx v1.6.7
making output directory...
loading translations [en]... done
/home/docs/checkouts/readthedocs.org/user_builds/anisocado/envs/latest/lib/python3.7/site-packages/sphinx/util/compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' instead.
  RemovedInSphinx17Warning)

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/anisocado/envs/latest/lib/python3.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/anisocado/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 196, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/anisocado/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/anisocado/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 196, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/anisocado/envs/latest/lib/python3.7/site-packages/sphinx_execute_code/__init__.py", line 81
    exec code
            ^
SyntaxError: Missing parentheses in call to 'exec'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/anisocado/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 196, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/anisocado/envs/latest/lib/python3.7/site-packages/sphinx_execute_code/__init__.py", line 81
    exec code
            ^
SyntaxError: Missing parentheses in call to 'exec'
The full traceback has been saved in /tmp/sphinx-err-ui9iv69y.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by spacemanspiff2007** [comment]
@jpsenior :
Could you push the package to pypi, please?
